set-name: 'Zephyr-DDR'

hart-entry-points: {
  u54_1: '0x80000000',
}

payloads:
  build/zephyr/zephyr.elf:    {
    exec-addr: '0x80000000',
    owner-hart: u54_1,
    priv-mode: prv_m,
    skip-opensbi: true,
    payload-name: "zephyr"
}
